apiVersion: v1
kind: Pod
metadata:
  name: hello-api-deploy
  labels:
    name: hello-api
spec:
  containers:
  - name: hello-api
    image: solwin/exp:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 3000
